### ISSUE TITLE
Tasks: Adjust Search UI JS

### ISSUE THREAD

**Issue by grvhi** [kartoza/catalogue#196]
# Tasks
- [x] Disable the search button until a date range has been added
- [x] Remove the satellite help span if it is not required (what error could be shown here?), or add the span programatically if it is required. Currently, the span adds unnecessary blank space.
- [x] Prevent the date widget from showing dates into the future (or prevent the user from selecting future dates if the widget can't disable them).
- [x] Please make the Date Range title link red if no date range is entered and return it to blue once a range is selected.
- [x] Populate search help and convert both help modals to BS modals - please add the necessary .modal-body classes
- [x] Add tooltips to all buttons - @icrni: please change "div" to "button" or "a" so the tooltips can work
- [x] ⌵ icons should trigger ~~accordion toggle~~ satellites drop down
