### ISSUE TITLE
The new (v3) site implementation needs to be reviewed and a workplan for completion made

### ISSUE THREAD

**Issue by timlinux** [kartoza/catalogue#2]
# Problem

Version 3 of the website needs to be rock solid before we can roll it out. The existing implmentation needs to be reviewed and all outstanding issues need to be clearly documented here on GH.
# Proposed solution

I am proposing that we have a 'ticket sprint' that focusses entirely on missing / broken functionality in the current code base. The sprint participants should document each issue in a form similar to used in this ticket (Problem, Proposed Solution, Expected Outcome, CC).
# Expected outcome

After the ticket sprint the following should be in place:
- [ ] A comprehensive requirements list needed for the release of v3.
- [ ] All tickets should be atomic (i.e. describing only a single unit of work)
- [ ] All tickets should be well structured
- [ ] Tickets should not be assigned any particular milestone - we will do this on a sprint by sprint basis
- [ ] Tickets should not include 'wishlist' items, but should rather focus on the specific steps need to achieve feature parity with V2 and to make the site functional.
# CC

@Erve1879 
@lkleyn
