### ISSUE TITLE
Migration plan for Catalogue V3

### ISSUE THREAD

**Issue by timlinux** [kartoza/catalogue#214]
This ticket serves as a record for our plans to migrate the catalogue to new infrastructure hosted at SANSA

Key elements:
- We will split the software components onto different hardware components
- We will migrate away from legacy hardware (LION, ELEPHANT, RHINO) in a phased manner
- We aim to hand over management of all hardware and software deployments to SANSA. Linfiniti will produce the software, SANSA will host, monitor and deploy it on their infrastructure.
- We will provide SANSA with scripts to automate deployment of the catalogue and attendant services and provide documentation describing how to deploy the individual components.
# Phase 1: Migration for the first week of March 2014
## Goals:
- **Catalogue Testing VM  (http://41.74.158.4/)** hosted on **'Owl'**:
- New web mapping server (IP Unknown) hosted on **'Sparrow'**. 
  *
## Tasks"
- [ ] @timlinux to copy all thumbs to the new server and migrate them to the new naming scheme
- [ ] @timlinux to copy all downloadable products to the test VM
- [ ] Karabo to create map server VM. This machine should be the most powerful configuration you can accommodate and with minimum 20TB (initial estimate) and as many CPU's as you can allocate it.
- [ ] Karabo to copy all Mosaics from `lion:/mnt/cataloguestorage2/gisdata/za/SPOT*/tif10m` to the lustrefs that is attached to the new mapping server / VM
- [ ] @timlinux to start generation of 2011 10m mosaic on the maps.sansa.org.za server and to script the process via a fabric command.
- [ ] @lkleyn  to process subsequent mosaics into tilesets on production environment
- [ ] @lkleyn to copy all tilesets over to DMZ lustre FS which must be attached to mapping server
- [ ] Karabo ensure test.catalogue.sansa.org.za points to the test VM
- [ ] Karabo ensure test.maps.sansa.org.za  points to the maps server VM
# Phase 2: Going live at the end of March 2014
## Goals:
- We will clone the test VM for the live server. The live clone will also be hosted on **'Owl'**.  **DNS:** catalogue.sansa.org.za will be repointed to the live VM when it enters into production.
# Phase 3: ETA unknown. Complete migration to new hardware infrastructure.
## Goals:
- Migrate all downloadable products to SANSA FTP server and off catalogue VM storage
